# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landslide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='energy',
            new_name='daya',
        ),
        migrations.RemoveField(
            model_name='data',
            name='frekuensi',
        ),
        migrations.RemoveField(
            model_name='data',
            name='total_energy',
        ),
    ]
